CREATE TABLE "GAB_5947_CUSTRFQ" (
 "RFQ" CHAR(7) NOT NULL,
 "LINE_RFQ" CHAR(3) NOT NULL,
 "NOTES" VARCHAR(5000),
 "SALESPERSON" VARCHAR(30),
 "BUYER" VARCHAR(30),
 "RFQ_DUE_DATE" VARCHAR(25),
 "ENGINEER" VARCHAR(30),
 "STATUS" VARCHAR(30),
 "RFQ_DATE" VARCHAR(10),
 "RFQ_TIME" VARCHAR(50) );